<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hh_simple_downloadcounter"
 *
 * Auto generated by Extension Builder 2019-01-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['hh_simple_downloadcounter'] = [
    'title' => 'Hauer-Heinrich - Simple Downloadcounter',
    'description' => 'Adds a Backend module to list downloaded files with count',
    'category' => 'Backend module',
    'author' => 'Christian Hackl',
    'author_email' => 'web@hauer-heinrich.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
    'autoload' => [
        'psr-4' => [
            'HauerHeinrich\\HhSimpleDownloadcounter\\' => 'Classes'
        ],
    ],
];
